name: Linux
on: [push]
jobs:
  gcc:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        cfgopt:
          - ""
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: nm-wu/nsf
          token: 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
      - name: Download Tcl tarball
        run: |
          curl -L -k -o tcl.tar.gz https://core.tcl-lang.org/tcl/tarball/tcl.tar.gz?uuid=core-8-6-branch
          tar -xzf tcl.tar.gz
          ls -la
      - name: Configure ${{ matrix.cfgopt }}
        run: |
          mkdir "${GITHUB_WORKSPACE}/build"
          ./configure ${CFGOPT} --prefix=${GITHUB_WORKSPACE}/tcl/unix  --exec-prefix=${GITHUB_WORKSPACE}/tcl/unix || (cat config.log && exit 1)
        working-directory: tcl/unix
        env:
          CFGOPT: ${{ matrix.cfgopt }}
      - name: Build + install
        run: |
          make all
          make install
        working-directory: tcl/unix
      - name: Configure ${{ matrix.cfgopt }}
        run: |
          ls -la /Users/ssoberni/Documents/dev/nsf/tcl/unix/lib/
          ls -la ${GITHUB_WORKSPACE}/tcl/unix/lib
          ./configure ${CFGOPT} --prefix=${GITHUB_WORKSPACE}/build --with-tcl=${GITHUB_WORKSPACE}/tcl/unix/lib || (cat config.log && exit 1)
        env:
          CFGOPT: ${{ matrix.cfgopt }}
      - name: Build + tests
        run: |
          make test
